[target.'cfg(all())']
rustflags = [
  "-Wclippy::all",
  "-Wclippy::cargo",
  "-Wclippy::pedantic",
  # restrictions
  "-Wclippy::dbg_macro",
  "-Wclippy::unwrap_used",
  "-Wclippy::empty_drop",
  "-Wclippy::exit",
  "-Wclippy::empty_structs_with_brackets",
  "-Wclippy::rc_buffer",
  "-Wclippy::rc_mutex",
  "-Wclippy::same_name_method",
  # FIXME:
  "-Aclippy::unwrap_used",
  "-Aclippy::missing_panics_doc"
]
