name: Release Binaries

permissions: {}

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    if: github.repository_owner == 'Boshen'
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04

          - target: aarch64-unknown-linux-musl
            os: ubuntu-22.04

          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04

          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04

          - target: x86_64-unknown-freebsd
            os: ubuntu-22.04

          - target: aarch64-apple-darwin
            os: macos-latest

          - target: x86_64-apple-darwin
            os: macos-latest

          - target: universal-apple-darwin
            os: macos-latest

          - target: aarch64-pc-windows-msvc
            os: windows-latest

          - target: x86_64-pc-windows-msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - name: Set environment variables
        run: |
          VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          echo "SHEAR_VERSION=$VERSION" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV # for mimalloc

      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16

      - uses: taiki-e/setup-cross-toolchain-action@d62f33b587e73b0004731caebc7d2d46b18a7567 # v1.39.2
        with:
          target: ${{ matrix.target }}

      - run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static -C link-self-contained=yes" >>"${GITHUB_ENV}"
        if: contains(matrix.target, '-linux-musl')

      - uses: taiki-e/upload-rust-binary-action@f0d45ae91ee7b8ee928de7a9d04d893a08bcbec6 # v1.30.2
        with:
          bin: cargo-shear
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          features: allocator
          token: ${{ secrets.GITHUB_TOKEN }}
